services:
  interface:
    build: https://github.com/adipginting/industrialisasi-interface.git#main
    restart: always
    ports:
      - "3000:3000"
  api:
    build: https://github.com/adipginting/industrialisasi-apis.git#main
    restart: always
    environment:
      - "PGHOST=${PGHOST}"
      - "PGUSER=${PGUSER}"
      - "PGDATABASE=${PGDATABASE}"
      - "PGPORT=${PGPORT}"
      - "PGPASSWORD=${PGPASSWORD}"
      - "GMAILUSER=${GMAILUSER}"
      - "GMAILPASSWORD=${GMAILPASSWORD}"
      - "PRODUCTION=${PRODUCTION}"
    ports:
      - "4000:4000"
  redoc:
    image: redocly/redoc
    restart: always
    environment:
      - "SPEC_URL=industrialisasi.yaml"
    volumes:
      - ./industrialisasi.yaml:/usr/share/nginx/html/industrialisasi.yaml
    ports:
      - "5000:80"
  database:
    image: postgres:latest
    restart: always
    environment:
      - "POSTGRES_USER=${PGUSER}"
      - "POSTGRES_PASSWORD=${PGPASSWORD}"
      - "POSTGRES_DB=${PGDATABASE}"
    ports:
      - "${PGPORT}:${PGPORT}"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - database_volume:/var/lib/postgresql/14/main/

volumes:
  database_volume:
    driver: local
